[package]
name = "chimpdao-pocket-factory"
edition.workspace = true
license.workspace = true
publish = false
version = "1.0.0"

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
chimpdao-chip-auth = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
