version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: "bun"
    directory: "/dapp"
    schedule:
      interval: "monthly"
    groups:
      npm-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: "bun"
    directory: "/nfc-server"
    schedule:
      interval: "monthly"
    groups:
      npm-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      cargo-minor:
        update-types:
          - minor
          - patch
