[workspace]
members = ["contracts/*", "examples/*"]
resolver = "2"

[workspace.package]
authors = ["ChimpDAO"]
edition = "2024"
license = "BSD-3-Clause"
repository = "https://radicle.consulting-manao.com/z2BaY97Uo8HiE2MbcibmgpWpfas2D"

[workspace.dependencies.soroban-sdk]
version = "26.1.0"

[workspace.dependencies.chimpdao-chip-auth]
path = "contracts/chip-auth"


[profile.release]
opt-level = "z"
debug = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
overflow-checks = true
strip = true

[profile.release-with-logs]
debug-assertions = true
inherits = "release"
