.PHONY: help install contract_build contract_test contract_bindings contract_deploy_collection contract_deploy_nft contract_help
.DEFAULT_GOAL := help
SHELL:=/bin/bash

ifndef network
   override network = testnet
endif

ifndef admin
   override admin = me
endif

ifndef wasm
override wasm = target/wasm32v1-none/release/nfc_nft.wasm
endif

ifndef wasm_collection
override wasm_collection = target/wasm32v1-none/release/collection.wasm
endif

# Add help text after each target name starting with '\#\#'
help:   ## show this help
	@echo -e "Help for this makefile\n"
	@echo "Possible commands are:"
	@grep -h "##" $(MAKEFILE_LIST) | grep -v grep | sed -e 's/\(.*\):.*##\(.*\)/    \1: \2/'

install:  ## install Rust and Soroban-CLI
	# uv for the pre-push hook
	curl -LsSf https://astral.sh/uv/install.sh | sh
	# install Rust
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh && \
	# install Soroban and config
	rustup target add wasm32v1-none && \
	cargo install --locked stellar-cli

funds:
	stellar keys fund $(admin) --network $(network)

# --------- CONTRACT BUILD/TEST/DEPLOY --------- #

contract_build:
	stellar contract build --optimize
	@ls -l target/wasm32v1-none/release/*.wasm

contract_test:
	cargo test

contract_bindings: contract_build  ## Create bindings
	stellar contract bindings typescript \
		--network $(network) \
		--wasm $(wasm) \
		--output-dir dapp/packages/nfc_nft \
		--overwrite && \
	cd dapp/packages/nfc_nft && \
	bun install --latest && \
	bun run build && \
	cd ../../.. && \
	stellar contract bindings typescript \
		--network $(network) \
		--wasm $(wasm_collection) \
		--output-dir dapp/packages/collection \
		--overwrite && \
	cd dapp/packages/collection && \
	bun install --latest && \
	bun run build && \
	cd ../.. && \
	bun format

# --salt $(shell printf chi1 | openssl sha256 | cut -d " " -f2) \

contract_deploy_collection:  ## Deploy Soroban contract collection to testnet
	stellar contract deploy \
  		--wasm $(wasm_collection) \
  		--source-account me \
  		--network $(network) \
  		-- \
  		--admin me \
  		> .config/stellar/collection_$(network)_id && \
  	cat .config/stellar/collection_$(network)_id

contract_deploy_nft:  ## Deploy Soroban contract NFT to testnet
	stellar contract deploy \
  		--wasm $(wasm) \
  		--source-account me \
  		--network $(network) \
  		-- \
  		--admin me \
  		--name "Palta Chimpy" --symbol chi1 --max_tokens 100 \
  		--uri https://ipfs.io/ipfs/bafybeiafq44zqj626slkz72c3xe2c2cnqnygmiev7uz33jbxoxd3trrw34 \
  		> .config/stellar/nfc_nft_$(network)_id && \
  	cat .config/stellar/nfc_nft_$(network)_id

contract_uri:
	stellar contract invoke \
		--source-account me \
		--network $(network) \
		--id $(shell cat .config/stellar/nfc_nft_$(network)_id) \
		-- \
		token_uri \
		--token_id 0
